name: post-price-cron-job
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: yarn install, build and run
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          BS_USERNAME: ${{ secrets.BS_USERNAME }}
          BS_PASSWORD: ${{ secrets.BS_PASSWORD }}
        run: |
          yarn 
          yarn build
          node dist/price.js
